### ISSUE TITLE
Just a little more documentations would be greet

### ISSUE THREAD

**Issue by jay51** [En14c/scylla#1]
would love to see some read me or if you could point to some resource to explain the various components in the project.

**Comment by En14c** [comment]
hey bro sorry have been away and a bit busy for the last 2 months (final exams, work, etc...).

**Books (for concepts etc...)**

- Modern Operating Systems (4th Edition)
- Operating Systems the 3 easy peaces (very recommended)

**Resources to start implementing a simple kernel**

- [OSDev Wiki](https://wiki.osdev.org/Expanded_Main_Page)
- [MIT OS course](https://pdos.csail.mit.edu/6.828/2019/xv6.html)
- Intel architecture software developer's manual, volume 3

**What have been done so far in Scylla**

- screen driver (we use the VGA text mode)
- GDT initialization
- IDT initialization, PIC and PIT initialization (we have a working interrupt systems now)
- get physical memory mapping as well as calculating the size of usable physical memory from this mapping
- physical memory manager

**Next milestones**

- paging and virtual memory manager with a kernel heap for allocating small objects etc...
- virtual file system and some drivers for some specific file system like (ext2, etc...)
- keyboard driver
- transition to user mode
- process abstraction, syscalls and our first process running in user mode (shell)

PS:
please note that um learning by doing and um not an expert so there might be some resources better than the ones i listed (and um sure there is), so just take these resources as a starting point for further tinkering and googling.

**Comment by jay51** [comment]
Thank you!
